[colors.primary]
background = '#0a1b1f'
foreground = '#839395'

# Normal colors
[colors.normal]
black   = '#003440'
red     = '#db312f'
green   = '#859801'
yellow  = '#b48800'
blue    = '#268ad1'
magenta = '#d23581'
cyan    = '#2aa097'
white   = '#eee7d4'

# Bright colors
[colors.bright]
black   = '#586d74'
red     = '#ca4a16'
green   = '#586d74'
yellow  = '#657a82'
blue    = '#839395'
magenta = '#6c6ec6'
cyan    = '#93a0a0'
white   = '#fdf5e2'
