import = [
  "~/.config/alacritty/themes/base16_default_dark.toml"
]

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 20

[font.normal]
family = "CodeNewRoman Nerd Font"

[font.glyph_offset]
x = 1
y = 1

[font.offset]
x = 1
y = 1

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login", "--command", "tmux new-session -A -D -s main"]

[window]
decorations = "transparent"
decorations_theme_variant = "light"
dynamic_padding = false
dynamic_title = true
opacity = 0.98
blur = false

[window.dimensions]
columns = 120
lines = 20

[window.padding]
x = 5
y = 5

[scrolling]
multiplier = 2

[keyboard]
bindings = [
  { key = "T", mods = "Command", chars = "\u0002c" },
  { key = "W", mods = "Command", chars = "\u0002x" },
  { key = "]", mods = "Command", chars = "\u0002n" },
  { key = "[", mods = "Command", chars = "\u0002p" },
  { key = "D", mods = "Command", chars = "\u0002%" },
  { key = "H", mods = "Command", chars = "\u0002h" },
  { key = "K", mods = "Command", chars = "\u0002k" },
  { key = "J", mods = "Command", chars = "\u0002j" },
  { key = "L", mods = "Command", chars = "\u0002l" },
  { key = "1", mods = "Command", chars = "\u00021" },
  { key = "2", mods = "Command", chars = "\u00022" },
  { key = "3", mods = "Command", chars = "\u00023" },
  { key = "4", mods = "Command", chars = "\u00024" },
  { key = "5", mods = "Command", chars = "\u00025" },
  { key = "6", mods = "Command", chars = "\u00026" },
  { key = "7", mods = "Command", chars = "\u00027" },
  { key = "8", mods = "Command", chars = "\u00028" },
  { key = "9", mods = "Command", chars = "\u00029" },
]
